# Generated by Django 5.2 on 2025-05-06 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_reoccuring_event_start_date_event_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
    ]
